name: using composite
on: 
  push:
    branches:
      - "**"
jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name:  "itd steps 2"
        uses: vamsins/githubactionsss/.github/actions/greet@main
        
  greeting-job1:
    runs-on: ubuntu-latest
    steps:
      - name:  "itd steps 3"
        uses: vamsins/githubactionsss/.github/actions/greet@main
        with:
          username: "vamsi"
